// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations run over Supabase's session-mode pooler (port 5432), not the
    // transaction-mode pooler the app uses at runtime (DATABASE_URL, port
    // 6543) — transaction mode doesn't reliably support the advisory locks
    // and prepared statements `migrate` needs, and hangs instead of erroring.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
